#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL

CREATE DATABASE $WEBAPOLLO_DB_NAME;
CREATE USER $WEBAPOLLO_DB_USERNAME WITH PASSWORD '$WEBAPOLLO_DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE $WEBAPOLLO_DB_NAME to $WEBAPOLLO_DB_USERNAME;

EOSQL
