FROM gmod/apollo:latest

#RUN cd /usr/local/tomcat/webapps/root/jbrowse/plugins
# extract war before tomcat, so we can add plugins to it - probably this should
# be done in the apollo build, not sure how to extend it though

RUN cd ${CATALINA_BASE}/webapps && \
    mkdir ${CATALINA_BASE}/webapps/ROOT && \
    unzip ${CATALINA_BASE}/apollo.war -d ${CATALINA_BASE}/webapps/ROOT && \
    rm ${CATALINA_BASE}/apollo.war


COPY JBrowse/plugins/ ${CATALINA_BASE}/webapps/ROOT/jbrowse/plugins/

RUN cd ${CATALINA_BASE}/webapps/ROOT/jbrowse/plugins && \
     unzip \*.zip && \
     rm *.zip && \
     mkdir GCContent MultiBigWig TrackScorePlugin SmallRNAPlugin && \
     mv gccontent-master/* GCContent/ && \
     mv jbplugin-smallrna-master/* SmallRNAPlugin && \
     mv jbplugin-trackscores-master/* TrackScorePlugin && \
     mv multibigwig-master/* MultiBigWig && \
     cd ${CATALINA_BASE}/webapps/ROOT/jbrowse && \
     bash setup.sh

# groovy needed for scripts
RUN apt-get update && apt-get -y install groovy

# Pulling SAMTools from its repository, unpacking the archive and installing
 RUN wget https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2 \
 && tar jxf samtools-1.2.tar.bz2 \
 && cd samtools-1.2 \
 && make \
 && make install

 # install perl and modules
 RUN apt-get install -y make
 RUN apt-get install -y perl
 RUN apt-get install -y cpanminus

 RUN cpanm -v JSON
 RUN cpanm -v LWP::Simple
 RUN cpanm -v File::Copy
 RUN cpanm -v Getopt::Long
 RUN cpanm -v Data::Dumper
 RUN cpanm -v URI::Escape
# #RUN cpanm -v CBIL::Util 


# copy in needed jbrowse scripts
COPY  JBrowse/bin/dumpConfigurationsForApollo.pl ./
COPY  JBrowse/bin/makeGroovyAddOrganismCommands.pl ./

# copy in apollo-config.groovy (needed for one line, default group for new users)
COPY apollo_files/apollo-config.groovy ${CATALINA_BASE}/webapps/ROOT/WEB-INF/classes/apollo-config.groovy

COPY apollo_files/jbrowse.conf ${CATALINA_BASE}/webapps/ROOT/jbrowse/
