FROM gmod/apollo:latest

#RUN cd /usr/local/tomcat/webapps/root/jbrowse/plugins
# extract war before tomcat, so we can add plugins to it - probably this should
# be done in the apollo build, not sure how to extend it though

RUN cd ${CATALINA_BASE}/webapps && \
    mkdir ${CATALINA_BASE}/webapps/ROOT && \
    unzip ${CATALINA_BASE}/apollo.war -d ${CATALINA_BASE}/webapps/ROOT && \
    rm ${CATALINA_BASE}/apollo.war


COPY JBrowse/plugins/ ${CATALINA_BASE}/webapps/ROOT/jbrowse/plugins/

RUN cd ${CATALINA_BASE}/webapps/ROOT/jbrowse/plugins && \
     unzip \*.zip && \
     rm *.zip && \
     mkdir GCContent MultiBigWig TrackScorePlugin SmallRNAPlugin && \
     mv gccontent-master/* GCContent/ && \
     mv jbplugin-smallrna-master/* SmallRNAPlugin && \
     mv jbplugin-trackscores-master/* TrackScorePlugin && \
     mv multibigwig-master/* MultiBigWig && \
     cd ${CATALINA_BASE}/webapps/ROOT/jbrowse && \
     bash setup.sh

# groovy needed for scripts
RUN apt-get update && apt-get -y install groovy

# BLAT and faToTwoBit needed for BLAT searches
RUN curl -s "http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/blat" -o /usr/local/bin/blat && \
    chmod +x /usr/local/bin/blat && \
    curl -s "http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToTwoBit" -o /usr/local/bin/faToTwoBit && \
    chmod +x /usr/local/bin/faToTwoBit

# copy in needed jbrowse scripts

# copy in apollo-config.groovy (needed for one line, default group for new users)
COPY apollo_files/apollo-config.groovy ${CATALINA_BASE}/webapps/ROOT/WEB-INF/classes/apollo-config.groovy

COPY apollo_files/jbrowse.conf ${CATALINA_BASE}/webapps/ROOT/jbrowse/
